### ISSUE TITLE
=dev-util/webstorm-2017* failing to build due to error in path

### ISSUE THREAD

**Issue by ghost** [fmoro/faustoo#2]
ebuild  trying to use dev-util/webstorm-2017.1.0.171.3780.79/image//opt/webstorm/jre/jre/bin
when it should be:
dev-util/webstorm-2017.1.0.171.3780.79/image/opt/webstorm/jre/bin

chmod: cannot access ‘/<portage_tmp_dir>/dev-util/webstorm-2017.1.0.171.3780.79/image//opt/webstorm/jre/jre/bin’: No such file or directory

**Comment by ghost** [comment]
ls /var/tmp/portage/dev-util/webstorm-2017.1.0.171.3780.79/image/opt/webstorm/jre/
java  jjs  keytool  orbd  pack200  policytool  rmid  rmiregistry  servertool  tnameserv  unpack200

as you can see there is no jre/jre/bin but jre/bin

**Comment by fmoro** [comment]
WoW, I test It and it compiled fine for me... Could you tell me what USE
flags are you using. I supone that I was using system jre and you the one
provided by the package, isn't It?

**Comment by fmoro** [comment]
Sadly I am at work now. I Will fix it as soon as I arrive home (about 17:30 18:00 UTC). I am really sorry about this.

**Comment by ghost** [comment]
thats with custom-jdk use enabled.

**Comment by fmoro** [comment]
It should be fixed now, Oleg. I have test it and it works for me.
