### ISSUE TITLE
app-editors/visual-studio-code missing x11-libs/libXScrnSaver RDEPEND

### ISSUE THREAD

**Issue by ghost** [fmoro/faustoo#3]
reference report:
https://bugs.funtoo.org/browse/FL-4581
it could be that some other x11-libs/ runtime dependencies are missing too.

**Comment by fmoro** [comment]
Thank you very much, oleg.
I have add every package that provide every library symlinked in VSC binaries. It should work in all fresh installs.

**Comment by ghost** [comment]
please, close.
